<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      const { log } = console
      const list = [1, 2, 3, 4, 5, 6]
      // function test() {
      //   for (let i = 0; i < list.length; i++) {
      //     if (list[i] == 3) {
      //       break
      //       // return
      //     }
      //     console.log(list[i])
      //   }
      // }
      // for (let i = 0; i < list.length; i++) {
      //   if (list[i] == 3) {
      //     // break
      //     return // SyntaxError: Illegal return statement  return 只能用在函数中
      //   }
      //   // return  // SyntaxError: Illegal return statement  return 只能用在函数中
      //   console.log(list[i])
      // }
      // 可以 return  如果真要中断，可以使用 try catch throw new error 的方式
      // list.reduce((cur, next) => {
      //   if (next == 3) {
      //     return
      //   }
      //   console.log('def', next)
      // }, 0)
      // 报错 Uncaught SyntaxError: Illegal break statement
      // list.reduce((cur, next) => {
      //   if (next == 3) {
      //     break
      //   }
      //   console.log('def', next)
      // }, 0)
      // 报错 Uncaught SyntaxError: Illegal continue statement: no surrounding iteration statement
      // list.reduce((cur, next) => {
      //   if (next == 3) {
      //     continue
      //   }
      //   console.log('def', next)
      // }, 0)
      // 报错 Uncaught SyntaxError: Illegal break statement
      // list.reduce((cur, next) => {
      //   if (next == 3) {
      //     break
      //   }
      //   console.log('def', next)
      // }, 0)
      // 总结：map 只能 return 。map return 没什么研究意义，因为 map 本来就是要 return 返回数据，其他的 api 也是如此。
      // break，continue 报错  如果真要中断，可以使用 try catch throw new error 的方式
      // 可以 return
      // const a = list.map(v => {
      //   if (v == 3) {
      //     return v // 这里 return 了，下面的语句自然不执行
      //   }
      //   log('def', v) // def 1 2 4 5 6
      //   return v
      // })
      // log(a) // [1, 2, 3, 4, 5, 6]
      // 报错 Uncaught SyntaxError: Illegal break statement
      // list.map((v) => {
      //   if (v == 3) {
      //     break
      //   }
      //   console.log('def')
      // })
      // log(a)
      // 报错 Uncaught SyntaxError: Illegal continue statement: no surrounding iteration statement
      // list.map((v) => {
      //   if (v == 3) {
      //     continue
      //   }
      //   console.log('def')
      // })
      // log(a)
      // 总结：forEach 只能 return 。 break，continue 报错  如果真要中断，可以使用 try catch throw new error 的方式
      // 可以 return
      // list.forEach(v => {
      //   if (v == 3) {
      //     return // 这里 return 了，下面的语句自然不执行，但是循环依旧继续 相当于起到了 break 的作用。 node 环境相同
      //   }
      //   log('def', v) // def 1 2 4 5 6
      // })
      // function test(params) {
      //   list.forEach(v => {
      //     if (v == 3) {
      //       return // 这里 return 了，下面的语句自然不执行，但是循环依旧继续 相当于起到了 break 的作用。 node 环境相同
      //     }
      //     log('def', v) // def 1 2 4 5 6
      //   })
      // }
      // 报错 Uncaught SyntaxError: Illegal break statement
      // list.forEach((v) => {
      //   if (v == 3) {
      //     break
      //   }
      //   console.log('def')
      // })
      // 报错 Uncaught SyntaxError: Illegal continue statement: no surrounding iteration statement
      // list.forEach((v) => {
      //   if (v == 3) {
      //     continue
      //   }
      //   console.log('def')
      // })
      // test()
    </script>
  </body>
</html>
